[package]
name = "relrc"
version = "0.1.0"
edition = "2021"
description = "Reference counted pointers, with relationships to other pointers."
readme = "README.md"
license = "Apache-2.0"

[dependencies]
derive_more = "0.99.18"
